# Generated by Django 3.2.18 on 2023-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
