# Generated by Django 3.2.18 on 2023-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='drinks',
            field=models.BooleanField(default=False),
        ),
    ]
