# Generated by Django 3.2.18 on 2023-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0003_item_drinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='featured',
            new_name='breakfast',
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
