# Generated by Django 3.2.18 on 2023-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0005_auto_20230329_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='preview_price',
            field=models.CharField(default='0.00', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
