# Generated by Django 3.2.18 on 2023-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0006_auto_20230403_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(auto_now=True),
        ),
    ]
