# Generated by Django 3.2.18 on 2023-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0007_alter_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='breakfast',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/banner3.png', null=True, upload_to=''),
        ),
    ]
