# Generated by Django 3.2.18 on 2023-04-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0009_auto_20230406_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, default='/static/images/banner3.png', max_length=850, null=True),
        ),
    ]
