# Generated by Django 3.2.18 on 2023-04-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0010_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('count', models.CharField(max_length=1000)),
            ],
        ),
    ]
