# Generated by Django 3.2.18 on 2023-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0011_datacount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Event', max_length=400),
        ),
    ]
