# Generated by Django 3.2.18 on 2023-04-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0017_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='images',
            new_name='image',
        ),
    ]
