# Generated by Django 3.2.18 on 2023-04-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0018_rename_images_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bar_menu_listed',
            field=models.CharField(default='this are the bar menu listed below', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='champagne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='cocktails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='cognac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='milk_shakes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='mocktails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='shisha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='slippery_signatures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='smoothies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='soft_drinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='tequila',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='vape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='whiskey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='wines',
            field=models.BooleanField(default=False),
        ),
    ]
